index:
    path: /food
    controller: App\Controller\PlateController::searchingFood
    methods: [GET]

detail:
    path: /food/detail/{searchFood}
    controller: App\Controller\PlateController::searchingFoodDetail
    methods: [GET]
    defaults:
        searchFood: ''